version: '3'

services:
  web:
    build:
      context: ./movie-service  # Relative path to the movie-service folder
      dockerfile: dev.Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./movie-service:/app  # Map the volume for the code in the movie-service folder
    ports:
      - "8000:8000"
