# Generated by Django 4.0.10 on 2024-02-12 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procontentcreatorpermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': (('create_movie', 'Create Movie'), ('update_movie', 'Update the contents'), ('delete_movie', 'Delete the contents'), ('read_all_my_movies', 'Read all the contents'))},
        ),
    ]
