# Generated by Django 4.0.10 on 2024-02-12 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_procontentcreatorpermissions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procontentcreatorpermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': (('create_movie', 'Create Movie'), ('update_movie', 'Update own movie'), ('delete_movie', 'Delete own movie'), ('read_all_my_movies', 'Read all own movies'))},
        ),
    ]
