openapi: 3.0.3
info:
  title: movie-service
  version: 0.0.0
paths:
  /movie-service/api/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - username: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /movie-service/api/v1/movies/:
    get:
      operationId: v1_movies_retrieve
      tags:
      - v1
      security:
      - username: []
      responses:
        '200':
          description: No response body
    post:
      operationId: v1_movies_create
      tags:
      - v1
      security:
      - username: []
      responses:
        '200':
          description: No response body
  /movie-service/api/v1/movies/{id}/:
    get:
      operationId: v1_movies_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - v1
      security:
      - username: []
      responses:
        '200':
          description: No response body
    put:
      operationId: v1_movies_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - v1
      security:
      - username: []
      responses:
        '200':
          description: No response body
  /movie-service/api/v1/movies/{id}/reviews/:
    get:
      operationId: v1_movies_reviews_list
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - v1
      security:
      - username: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'
          description: ''
  /movie-service/api/v1/movies/{id}/reviews/create/:
    post:
      operationId: v1_movies_reviews_create_create
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Review'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Review'
        required: true
      security:
      - username: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
          description: ''
  /movie-service/api/v1/movies/list2/:
    get:
      operationId: v1_movies_list2_list
      parameters:
      - name: cursor
        required: false
        in: query
        description: The pagination cursor value.
        schema:
          type: string
      tags:
      - v1
      security:
      - username: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedMovieList'
          description: ''
  /movie-service/api/v1/movies/reviews/{id}/:
    get:
      operationId: v1_movies_reviews_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - v1
      security:
      - username: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
          description: ''
    put:
      operationId: v1_movies_reviews_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Review'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Review'
        required: true
      security:
      - username: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
          description: ''
    patch:
      operationId: v1_movies_reviews_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedReview'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedReview'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedReview'
      security:
      - username: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
          description: ''
    delete:
      operationId: v1_movies_reviews_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - v1
      security:
      - username: []
      responses:
        '204':
          description: No response body
  /movie-service/api/v1/movies/stream/:
    get:
      operationId: v1_movies_stream_list
      description: |-
        API endpoint that allows stream platforms to be viewed or edited.

        This viewset automatically provides `list`, `create`, `retrieve`,
        `update`, and `destroy` actions.

        * `list`: Returns a list of all stream platforms.
        * `create`: Creates a new stream platform.
        * `retrieve`: Retrieves a specific stream platform.
        * `update`: Updates a specific stream platform.
        * `destroy`: Deletes a specific stream platform.

        ## Additional Info:
        - Only admins can edit stream platforms.
        - ...
      tags:
      - v1
      security:
      - username: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StreamPlatform'
          description: ''
    post:
      operationId: v1_movies_stream_create
      description: |-
        API endpoint that allows stream platforms to be viewed or edited.

        This viewset automatically provides `list`, `create`, `retrieve`,
        `update`, and `destroy` actions.

        * `list`: Returns a list of all stream platforms.
        * `create`: Creates a new stream platform.
        * `retrieve`: Retrieves a specific stream platform.
        * `update`: Updates a specific stream platform.
        * `destroy`: Deletes a specific stream platform.

        ## Additional Info:
        - Only admins can edit stream platforms.
        - ...
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StreamPlatform'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/StreamPlatform'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/StreamPlatform'
        required: true
      security:
      - username: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StreamPlatform'
          description: ''
  /movie-service/api/v1/movies/stream/{id}/:
    get:
      operationId: v1_movies_stream_retrieve
      description: Retrieve a specific stream platform by ID
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this stream platform.
        required: true
      - in: query
        name: id
        schema:
          type: integer
        description: Stream Platform ID
      tags:
      - v1
      security:
      - username: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StreamPlatform'
          description: ''
    put:
      operationId: v1_movies_stream_update
      description: |-
        API endpoint that allows stream platforms to be viewed or edited.

        This viewset automatically provides `list`, `create`, `retrieve`,
        `update`, and `destroy` actions.

        * `list`: Returns a list of all stream platforms.
        * `create`: Creates a new stream platform.
        * `retrieve`: Retrieves a specific stream platform.
        * `update`: Updates a specific stream platform.
        * `destroy`: Deletes a specific stream platform.

        ## Additional Info:
        - Only admins can edit stream platforms.
        - ...
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this stream platform.
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StreamPlatform'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/StreamPlatform'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/StreamPlatform'
        required: true
      security:
      - username: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StreamPlatform'
          description: ''
    patch:
      operationId: v1_movies_stream_partial_update
      description: |-
        API endpoint that allows stream platforms to be viewed or edited.

        This viewset automatically provides `list`, `create`, `retrieve`,
        `update`, and `destroy` actions.

        * `list`: Returns a list of all stream platforms.
        * `create`: Creates a new stream platform.
        * `retrieve`: Retrieves a specific stream platform.
        * `update`: Updates a specific stream platform.
        * `destroy`: Deletes a specific stream platform.

        ## Additional Info:
        - Only admins can edit stream platforms.
        - ...
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this stream platform.
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedStreamPlatform'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedStreamPlatform'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedStreamPlatform'
      security:
      - username: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StreamPlatform'
          description: ''
    delete:
      operationId: v1_movies_stream_destroy
      description: |-
        API endpoint that allows stream platforms to be viewed or edited.

        This viewset automatically provides `list`, `create`, `retrieve`,
        `update`, and `destroy` actions.

        * `list`: Returns a list of all stream platforms.
        * `create`: Creates a new stream platform.
        * `retrieve`: Retrieves a specific stream platform.
        * `update`: Updates a specific stream platform.
        * `destroy`: Deletes a specific stream platform.

        ## Additional Info:
        - Only admins can edit stream platforms.
        - ...
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this stream platform.
        required: true
      tags:
      - v1
      security:
      - username: []
      responses:
        '204':
          description: No response body
  /movie-service/api/v1/movies/user-reviews/:
    get:
      operationId: v1_movies_user_reviews_list
      tags:
      - v1
      security:
      - username: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'
          description: ''
components:
  schemas:
    Movie:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        platform:
          type: string
        title:
          type: string
          maxLength: 50
        storyline:
          type: string
          maxLength: 200
        created:
          type: string
          format: date-time
          readOnly: true
        avg_rating:
          type: number
          format: double
        number_rating:
          type: integer
      required:
      - created
      - id
      - platform
      - storyline
      - title
    PaginatedMovieList:
      type: object
      properties:
        next:
          type: string
          nullable: true
        previous:
          type: string
          nullable: true
        results:
          type: array
          items:
            $ref: '#/components/schemas/Movie'
    PatchedReview:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        review_user:
          type: string
          readOnly: true
        rating:
          type: integer
          maximum: 5
          minimum: 1
        description:
          type: string
          nullable: true
          maxLength: 200
        active:
          type: boolean
        created:
          type: string
          format: date-time
          readOnly: true
        update:
          type: string
          format: date-time
          readOnly: true
    PatchedStreamPlatform:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        movie:
          type: array
          items:
            $ref: '#/components/schemas/Movie'
          readOnly: true
        name:
          type: string
          maxLength: 30
        about:
          type: string
          maxLength: 150
        website:
          type: string
          format: uri
          maxLength: 100
    Review:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        review_user:
          type: string
          readOnly: true
        rating:
          type: integer
          maximum: 5
          minimum: 1
        description:
          type: string
          nullable: true
          maxLength: 200
        active:
          type: boolean
        created:
          type: string
          format: date-time
          readOnly: true
        update:
          type: string
          format: date-time
          readOnly: true
      required:
      - created
      - id
      - rating
      - review_user
      - update
    StreamPlatform:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        movie:
          type: array
          items:
            $ref: '#/components/schemas/Movie'
          readOnly: true
        name:
          type: string
          maxLength: 30
        about:
          type: string
          maxLength: 150
        website:
          type: string
          format: uri
          maxLength: 100
      required:
      - about
      - id
      - movie
      - name
      - website
  securitySchemes:
    username: []
