# Generated by Django 4.2.5 on 2023-09-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist_app", "0002_streamplatform_watchlist_delete_movie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streamplatform",
            name="about",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="streamplatform",
            name="website",
            field=models.URLField(max_length=100),
        ),
    ]
