# Generated by Django 4.2.5 on 2023-09-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist_app", "0003_alter_streamplatform_about_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="storyline",
            field=models.CharField(max_length=200),
        ),
    ]
