# Generated by Django 4.2.5 on 2023-09-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist_app", "0007_review_review_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="avg_rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="review",
            name="number_rating",
            field=models.IntegerField(default=0),
        ),
    ]
