# Generated by Django 4.2.5 on 2023-09-28 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "watchlist_app",
            "0009_remove_review_avg_rating_remove_review_number_rating_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("storyline", models.CharField(max_length=200)),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("avg_rating", models.FloatField(default=0)),
                ("number_rating", models.IntegerField(default=0)),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie",
                        to="watchlist_app.streamplatform",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="review",
            name="watchlist",
        ),
        migrations.DeleteModel(
            name="WatchList",
        ),
        migrations.AddField(
            model_name="review",
            name="movie",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="watchlist_app.movie",
            ),
            preserve_default=False,
        ),
    ]
