# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_login_verification.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1duser_login_verification.proto\";\n\x15UserValidationRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"H\n\x16UserValidationResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t2N\n\x0bUserService\x12?\n\x0cValidateUser\x12\x16.UserValidationRequest\x1a\x17.UserValidationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_login_verification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERVALIDATIONREQUEST']._serialized_start=33
  _globals['_USERVALIDATIONREQUEST']._serialized_end=92
  _globals['_USERVALIDATIONRESPONSE']._serialized_start=94
  _globals['_USERVALIDATIONRESPONSE']._serialized_end=166
  _globals['_USERSERVICE']._serialized_start=168
  _globals['_USERSERVICE']._serialized_end=246
# @@protoc_insertion_point(module_scope)
