# Generated by Django 4.2.5 on 2023-12-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplatform',
            name='about',
            field=models.CharField(max_length=300),
        ),
    ]
